Repository Farnooshmo/time-tracker, pull requests merged in 2024-02, with the labels that each got.

#43 Debugging the update in backend
  server/index.js
Labels: bug

#46 Edit todo btn
  client/src/components/EditTodo.js
  client/src/components/ListTodos.js
Labels: Front End

#51 Create a table for time_tracking
  server/database.sql
Labels: Back End

#76 meysam-67-Style-ListTodos.js
  client/src/App.css
  client/src/components/ListTodos.js
  client/src/components/Timer.js
Labels: Front End

#97 Store the date in the psql table
  server/index.js
Labels: bug
